name: Server Build & Deploy (Production)

on:
  push:
    branches:
      - master
    paths:
      - 'packages/server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.18.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      run: |
          npm install
          npm run test
