name: Web Build & Deploy (Production)

on:
  push:
    branches:
      - master
    paths:
      - 'packages/server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:10.12.0
    steps:
      - uses: actions/checkout@v1
      - name: Tests
        env:
          NODE_ENV: 'test'
        run: |
          npm install
          npm run test
